name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10" # Adjust this to match your project's Python version

    # Step 3: Install dependencies and test pip install
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .  # Test pip install .
